project: 
  type: website
  preview: 
    port: 4000

website: 
  title: "ivonesamplemr"
  repo-url: https://github.com/remlapmot/ivonesamplemr
  repo-branch: main
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.html
      - text: "Helpfile examples"
        menu:
        - text: "ivasmm"
          href: ivasmm-examples.html
        - text: "ivlsmm"
          href: ivlsmm-examples.html
        - text: "ivmsmm"
          href: ivmsmm-examples.html
        - text: "ivmw"
          href: ivmw-examples.html
        - text: "ivtsps"
          href: ivtsps-examples.html
        - text: "ivtsri"
          href: ivtsri-examples.html
        - text: "ivxtile"
          href: ivxtile-examples.html
      - text: "Helpfiles"
        menu:
        - text: "ivonesamplemr"
          href: ivonesamplemr-helpfile.html
        - text: "ivasmm"
          href: ivasmm-helpfile.html
        - text: "ivlsmm"
          href: ivlsmm-helpfile.html
        - text: "ivmsmm"
          href: ivmsmm-helpfile.html
        - text: "ivmw"
          href: ivmw-helpfile.html
        - text: "ivtsps"
          href: ivtsps-helpfile.html
        - text: "ivtsri"
          href: ivtsri-helpfile.html
        - text: "ivxtile"
          href: ivxtile-helpfile.html
        - text: "iv"
          href: iv-helpfile.html
      - text: "About"
        href: about.html
    right:
      - icon: github
        href: https://github.com/remlapmot/ivonesamplemr
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: mystyles.css
    toc: true
    highlight-style: arrow

freeze: false  # re-render only when source changes

# bibliography: refs.bib
